/*
  Sketch generated by the Arduino IoT Cloud Thing "Untitled"
  https://create.arduino.cc/cloud/things/e3652e97-c5ac-451c-9a38-e3cbcd2b0591

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when chhttps://docs.arduino.cc/static/a94a462df840d87411906381f90fa390/29114/cloud-esp32-img-16.pnganges are made to the Thing

  int cups;
  bool start_tea_making;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"

void setup() {
  // Initialize serial and wait for port to open:
  Serial.begin(9600);
  pinMode(2, OUTPUT);

  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500);

  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);

  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
  */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
}

void loop() {
  ArduinoCloud.update();
  // Your code here


}

void onPushButtonChange()  {
  Serial.print("Let's make ");
  Serial.print(cups);
  Serial.println(" cups of tea!");
  blink(1000);
  if (!start_tea_making){
    if (cups>=2 && cups<=6){
      
      Serial.println("Change ");
      start_tea_making = true;
      prepareTea(cups*250);
    }
  }
}

void prepareTea( int milliliters){
  for (int i=0;i<10;i++) blink(500);
  start_tea_making = false;
  return;
}

void blink(unsigned long ms){
  digitalWrite(2, HIGH);   
  delay(ms);                     
  digitalWrite(2, LOW); 
  
}


void onStartTeaMakingChange()  {
  // Add your code here to act upon StartTeaMaking change
}

void onCupsChange()  {
  // Add your code here to act upon Cups change
}